workflows:
  android-release:
    name: Build Android AAB
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Setup Gradle Wrapper and Build
        script: |
          gradle wrapper --gradle-version 8.2
          chmod +x gradlew
          ./gradlew bundleRelease --no-daemon -Dorg.gradle.jvmargs="-Xmx3072m -XX:MaxMetaspaceSize=512m"
    artifacts:
      - app/build/outputs/bundle/release/*.aab
      
