workflows:
  android-release:
    name: Build Android AAB
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Download Compatible Gradle
        script: |
          wget https://services.gradle.org/distributions/gradle-9.3.1-bin.zip
          unzip -q gradle-9.3.1-bin.zip
          export PATH=$PWD/gradle-9.3.1/bin:$PATH
          gradle -v
      - name: Build AAB
        script: |
          export PATH=$PWD/gradle-9.3.1/bin:$PATH
          gradle bundleRelease --no-daemon
    artifacts:
      - app/build/outputs/bundle/release/*.aab
      
